name: Generate Snake Animation
permissions:
  contents: write   # ✅ allows the workflow to push new branches/commits

on:
  schedule:
    - cron: "0 */12 * * *"   # runs every 12 hours
  workflow_dispatch:          # lets you run manually
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: denisthuo425-jude
          svg_out_path: dist/snake.svg

      - name: Commit & push snake to output branch
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: "chore: update snake animation"
          add: "dist/snake.svg"
          default_branch: output
          push: origin output --set-upstream
